### ISSUE TITLE
Incorrect Trigram Calculation

### ISSUE THREAD

**Issue by charxii** [ClemenPine/a200#7]
In `gendata.py`, you are adding `word_count` to `trigrams[seq]` every time you find a trigram instead of just increasing it by 1.

This also means that all the json files in the `data` directory are wrong. ex. `"ing": 7424670` in `data/monkeytype-10k.json` when there should only be 745.

```python
def get_trigrams(file: str):
    
    texts = json.load(open(file, 'r'))['texts']
    
    trigrams = {}

    counts = {
        'start': {},
        'end': {},
    }

    word_count = len(texts)
    for word in texts:

        padded_word = ' ' + word + ' '
        for i in range(len(padded_word) - 2):
            seq = padded_word[i:i+3]
            if not seq in trigrams:
                trigrams[seq] = word_count
            else:
                trigrams[seq] += word_count
```

**Comment by ClemenPine** [comment]
if I was only adding up trigrams within words then adding one to the total would be correct - but I'm also calculating the word boundary trigrams by pairing every end word with every start word. As a result every word appears n times instead of once to correctly weight word boundary trigrams with interword trigrams
